version: '3.8'  

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shope
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    environment:
      - DOCKER_ENV=true
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    depends_on:
      - backend
